[tools]
go = '1.25'
node = "24.2"
deno = '2.2'
rust = { version = "1.91", components = "rust-analyzer" }
java = '24.0'

uv = 'latest'

cosign = 'latest'
slsa-verifier = 'latest'

jujutsu = 'latest'
actionlint = 'latest'
awscli = 'latest'
bat = 'latest'
bazelisk = 'latest'
cmake = 'latest'
delta = 'latest'
direnv = 'latest'
fastfetch = 'latest'
fzf = 'latest'
gh = 'latest'
ghq = 'latest'
golangci-lint = 'latest'
helm = 'latest'
helmfile = 'latest'
jq = 'latest'
kubectl = 'latest'
kubesec = 'latest'
kustomize = 'latest'
neovim = 'latest'
ripgrep = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
stern = 'latest'
stylua = 'latest'
taplo = 'latest'
terraform = 'latest'
tmux = 'latest'
yq = 'latest'
protoc = 'latest'
protoc-gen-go = 'latest'

'npm:@google/gemini-cli' = 'latest'
'npm:@mermaid-js/mermaid-cli' = 'latest'
'npm:neovim' = 'latest'
'npm:typescript-language-server' = 'latest'
'npm:pyright' = 'latest'

'go:github.com/Kunde21/markdownfmt/v3/cmd/markdownfmt' = 'latest'
'go:github.com/aarzilli/gdlv' = 'latest'
'go:github.com/cespare/reflex' = 'latest'
'go:github.com/cweill/gotests/gotests' = 'latest'
'go:github.com/go-delve/delve/cmd/dlv' = 'latest'
'go:github.com/hashicorp/hcl/v2/cmd/hclfmt' = 'latest'
'go:github.com/x-motemen/gore/cmd/gore' = 'latest'
'go:golang.org/x/tools/cmd/goimports' = 'latest'
'go:golang.org/x/tools/gopls' = 'latest'
'go:oss.terrastruct.com/d2' = 'latest'
'go:github.com/Warashi/cage' = 'latest'

'aqua:LuaLS/lua-language-server' = 'latest'
'aqua:git-lfs/git-lfs' = 'latest'
'aqua:suzuki-shunsuke/pinact' = 'latest'
'aqua:goreleaser/goreleaser' = 'latest'
'aqua:anthropics/claude-code' = 'latest'

'pipx:isort' = 'latest'
'pipx:jupyterlab' = 'latest'
'pipx:huggingface_hub' = 'latest'

[settings]
experimental = true
http_timeout = '180s'
fetch_remote_versions_timeout = '60s'
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true
