[user]
name = "Shogo Iwano"
email = "shiwano@gmail.com"

[ui]
default-command = "status"
editor = "nvim"
pager = "delta"
paginate = "auto"
diff-formatter = ["delta", "--color-only"]
bookmark-list-sort-keys = ["name"]

[aliases]
s = ["status"]
b = ["bookmark"]
la = ["log", "-r", "all()"]
