[user]
name = "Shogo Iwano"
email = "shiwano@gmail.com"

[ui]
default-command = "status"
editor = "nvim"
pager = "delta"
paginate = "auto"
diff-formatter = ":git"
bookmark-list-sort-keys = ["name"]

[aliases]
cim = ["commit", "-m"]
cic = ["util", "exec", "--", "jj-describe-with-ai", "--commit"]
dim = ["describe", "-m"]
dic = ["util", "exec", "--", "jj-describe-with-ai", "--describe"]
la = ["log", "-r", "all()"]
lp = ["log", "-p", "all()"]
ls = ["log", "--stat", "all()"]
olp = ["op", "log", "-p"]
untrack = ["file", "untrack"]
fsm = ["debug", "watchman", "status"]

[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true
